---
- hosts: localhost
  become: yes
  tasks:
  - name: create a ansible node
    ec2:
     key_name: mykey03mar23
     instance_type: t2.micro
     image: ami-07b4dc31f864cc5e6
     wait: yes
     region: ap-northeast-1
     group: Ansible_SG_11may23
     count: 2
     vpc_subnet_id: subnet-0fe551cd46875ecae
     assign_public_ip: yes
     instance_tags:
         Name: AnsibleNode