---
- hosts: 172.31.1.220
  become: yes
  tasks: 
  - name: install git
    apt:
      name: git
      state: present

  - name: install tree
    apt:
      name: treeeeeeeeeeee 
      state: present
    ignore_errors: yes  

  - name: install wget
    apt:
      name: wget
      state: present         