---
- hosts: all
  become: yes
  tasks:
   - name: i want to ping all nodes
     ping:

   - name: i want to install webserver on ubuntu  ansible node
     apt:
      name: apache2
      state: present

   - name: i want to install wget on ubuntu ansible nodes
     apt:
      name: wget
      state: present
          