---
- hosts: 172.31.1.220
  become: yes
  tasks:
  - include: myfile.yml
  - include: myfile2.yml

  - name: install webserver
    apt:
     name: apache2
     state: present
    notify: restsrtwebserver

  - name: copy index file into node side
    copy:
      src: myindexpage
      dest: /var/www/html/index.html
    notify: restsrtwebserver      

  - name: copy dynamic files into nodes
    template:
        src: mydynamicindex.j2
        dest: /var/www/html/index.html
    notify: restsrtwebserver 

  - name: download internet files
    get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz 
        dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
        force_basic_auth: yes     

  handlers:
  - name: restsrtwebserver
    service:
       name: apache2
       state: restarted       