---
# tasks file for mywebrole
- name: install webserver on ubuntu
  apt:
   name: apache2 
   state: present 
  when: ansible_os_family=="Debian"

- name: install webserver on RedHat
  ansible.builtin.dnf:
    name: httpd 
    state: present 
  when: ansible_os_family=="RedHat"     